-- The forced first password change is gone, and with it the column that drove it.
--
-- It was never only a flag. POST /auth/password/initial set a password WITHOUT
-- proving the current one, and must_change_password was the only thing gating
-- that route — so dropping the flag and keeping the route would have turned it
-- into a password reset any signed-in session could call. Both went together.
--
-- Nothing is lost: POST /auth/password verifies the current credential through
-- passwordOpens(), which already handles an account that has never set one —
-- a member proves their national ID, an admin the password they were handed.
ALTER TABLE "profiles" DROP COLUMN "must_change_password";