export enum AttendanceRefusalReason {
  OUT_OF_RANGE = 'out_of_range',
  MOCK = 'mock',
  LOW_ACCURACY = 'low_accuracy',
  FACE_MISMATCH = 'face_mismatch',
  FACE_REQUIRED = 'face_required',
  LIVENESS = 'liveness',
  NOT_ENROLLED = 'not_enrolled',
  INTEGRITY_FAILED = 'integrity_failed',
  NOT_A_MEMBER = 'not_a_member',
  NO_SETTINGS = 'no_settings',
  QR_REQUIRED = 'qr_required',
  QR_DISABLED = 'qr_disabled',
  QR_INVALID = 'qr_invalid',
  OUTSIDE_SHIFT = 'outside_shift',
  OUTSIDE_WINDOW = 'outside_window',
  CHECKIN_CLOSED = 'checkin_closed',
  ALREADY_CHECKED_IN = 'already_checked_in',
  ALREADY_CHECKED_OUT = 'already_checked_out',
  NOT_CHECKED_IN = 'not_checked_in',
  BRANCH_BLOCKED = 'branch_blocked',
  GEOFENCE_ERROR = 'geofence_error',
}

export enum CommonErrorCode {
  NOT_FOUND = 'not_found',
  FORBIDDEN = 'forbidden',
  UNAUTHORIZED = 'unauthorized',
  BAD_REQUEST = 'bad_request',
  CONFLICT = 'conflict',
  INTERNAL_ERROR = 'internal_error',
  MEMBER_NOT_FOUND = 'member_not_found',
  INVALID_NATIONAL_ID = 'invalid_national_id',
  MISSING_NAME = 'missing_name',
  NATIONAL_ID_TAKEN = 'national_id_taken',
  BAD_BASE64 = 'bad_base64',
}
