-- GENERATED by scripts/extract-programmables.mjs from a reference database.
-- Functions, with their privileges. Authored ones live in 012.
-- Re-applied after every migration; every statement is idempotent.

CREATE OR REPLACE FUNCTION auth.email()
 RETURNS text
 LANGUAGE sql
 STABLE PARALLEL SAFE
AS $function$
  select nullif(auth.jwt() ->> 'email', '')::text
$function$;
revoke all on function auth.email() from public, anon, authenticated, service_role;
grant execute on function auth.email() to anon;
grant execute on function auth.email() to authenticated;
grant execute on function auth.email() to service_role;

CREATE OR REPLACE FUNCTION auth.jwt()
 RETURNS jsonb
 LANGUAGE sql
 STABLE PARALLEL SAFE
AS $function$
  select coalesce(nullif(current_setting('request.jwt.claims', true), ''), '{}')::jsonb
$function$;
revoke all on function auth.jwt() from public, anon, authenticated, service_role;
grant execute on function auth.jwt() to anon;
grant execute on function auth.jwt() to authenticated;
grant execute on function auth.jwt() to service_role;

CREATE OR REPLACE FUNCTION auth.role()
 RETURNS text
 LANGUAGE sql
 STABLE PARALLEL SAFE
AS $function$
  select nullif(auth.jwt() ->> 'role', '')::text
$function$;
revoke all on function auth.role() from public, anon, authenticated, service_role;
grant execute on function auth.role() to anon;
grant execute on function auth.role() to authenticated;
grant execute on function auth.role() to service_role;

CREATE OR REPLACE FUNCTION auth.uid()
 RETURNS uuid
 LANGUAGE sql
 STABLE PARALLEL SAFE
AS $function$
  select nullif(auth.jwt() ->> 'sub', '')::uuid
$function$;
revoke all on function auth.uid() from public, anon, authenticated, service_role;
grant execute on function auth.uid() to anon;
grant execute on function auth.uid() to authenticated;
grant execute on function auth.uid() to service_role;

CREATE OR REPLACE FUNCTION public.assert_member_codes_unique()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
declare
  dups int;
begin
  select count(*) into dups from (
    select member_code
    from public.member_directory
    where member_code is not null
    group by member_code
    having count(*) > 1
  ) d;
  if dups > 0 then
    raise exception 'member_code is not unique: % duplicated code(s)', dups;
  end if;
end $function$;

CREATE OR REPLACE FUNCTION public.assign_member_code()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
declare
  v_year   integer;
  v_inst   integer;
  v_prefix text;
  v_next   bigint;
begin
  -- A code is never edited by hand, by anyone: reads of a stale code must not
  -- be able to point at a different person later.
  if tg_op = 'UPDATE' then
    new.member_code := old.member_code;
  end if;

  select b.year, coalesce(inst.code, b.institution_code, 0)
    into v_year, v_inst
  from public."groups" b
  left join public.institutions inst on inst.id = b.institution_id
  where b.id = new.group_id;

  -- No group year means no code, same as before.
  if v_year is null then
    return new;
  end if;

  v_prefix := lpad(v_year::text, 4, '0') || lpad(coalesce(v_inst, 0)::text, 2, '0');

  -- Already carries a code for this year+institution: keep it.
  if new.member_code is not null and left(new.member_code, 6) = v_prefix then
    return new;
  end if;

  -- Take the next serial in this year+institution. The advisory lock serialises
  -- concurrent inserts into the same partition so two of them cannot read the
  -- same max(); the unique index above is the backstop if one ever slips.
  perform pg_advisory_xact_lock(hashtext('member_code:' || v_prefix));
  select coalesce(max(nullif(substring(member_code from 7), '')::bigint), 0) + 1
    into v_next
  from public.members
  where member_code like v_prefix || '%';

  new.member_code := public.compose_member_code(v_year, v_inst, v_next, null);
  return new;
end $function$;

CREATE OR REPLACE FUNCTION public.branches_set_geom()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
declare
  coords jsonb;
  ring   jsonb;
begin
  new.geom := ST_SetSRID(ST_MakePoint(new.longitude, new.latitude), 4326)::geography;

  if new.area_coords is not null
     and jsonb_typeof(new.area_coords) = 'array'
     and jsonb_array_length(new.area_coords) >= 3 then
    coords := new.area_coords;
    -- Close the ring if the last vertex isn't the first.
    if (coords -> (jsonb_array_length(coords) - 1)) is distinct from (coords -> 0) then
      coords := coords || jsonb_build_array(coords -> 0);
    end if;
    ring := (
      select jsonb_agg(jsonb_build_array((e ->> 'lng')::float8, (e ->> 'lat')::float8) order by ord)
      from jsonb_array_elements(coords) with ordinality as t(e, ord)
    );
    new.area := ST_SetSRID(
      ST_GeomFromGeoJSON(
        jsonb_build_object('type', 'Polygon', 'coordinates', jsonb_build_array(ring))::text
      ),
      4326
    )::geography;
  else
    new.area := null;
  end if;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.compose_member_code(p_year integer, p_institution_code integer, p_serial bigint, p_partition_size bigint)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
AS $function$
  select case when p_year is not null then
    lpad(p_year::text, 4, '0')
    || lpad(coalesce(p_institution_code, 0)::text, 2, '0')
    || lpad(
         p_serial::text,
         greatest(4, length(greatest(coalesce(p_partition_size, 0), p_serial)::text)),
         '0'
       )
  end;
$function$;

CREATE OR REPLACE FUNCTION public.geofence_check(p_branch uuid, p_lat double precision, p_lng double precision)
 RETURNS TABLE(distance_m double precision, radius_m integer, within boolean)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select
    case when h.area is not null then ST_Distance(h.area, g.pt)
         else ST_Distance(h.geom, g.pt) end as distance_m,
    h.radius_meters as radius_m,
    case when h.area is not null then ST_Covers(h.area, g.pt)
         else ST_DWithin(h.geom, g.pt, h.radius_meters) end as within
  from public.branches h
  cross join lateral (select ST_SetSRID(ST_MakePoint(p_lng, p_lat), 4326)::geography as pt) g
  where h.id = p_branch;
$function$;

CREATE OR REPLACE FUNCTION public.mark_left_work()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  auto_on boolean;
  now_cairo timestamp := (now() at time zone 'Africa/Cairo');
  changed integer := 0;
begin
  select auto_leave_work into auto_on from public.app_settings where id = 1;
  if not coalesce(auto_on, false) then
    return 0;
  end if;

  with cand as (
    select a.id,
           (a.date::timestamp
             + coalesce(sh.checkout_close, sh.end_time::time, time '23:59')
             + case
                 when sh.checkin_open is not null
                   and coalesce(sh.checkout_close, sh.end_time::time) < sh.checkin_open
                 then interval '1 day' else interval '0' end
           ) as deadline
      from public.attendance a
      left join public.shifts sh on sh.id = a.shift_id
     where a.check_in_at is not null
       and a.check_out_at is null
       and a.checkout_status is distinct from 'left_work'
       and a.date >= (now_cairo::date - 1)
  )
  update public.attendance a
     set checkout_status = 'left_work'
    from cand c
   where a.id = c.id
     and now_cairo > c.deadline;

  get diagnostics changed = row_count;
  return changed;
end;
$function$;
revoke all on function public.mark_left_work() from public, anon, authenticated, service_role;
grant execute on function public.mark_left_work() to service_role;

CREATE OR REPLACE FUNCTION public.roster_day_totals(p_year integer, p_month integer, p_branch_id uuid DEFAULT NULL::uuid, p_search text DEFAULT ''::text, p_field text DEFAULT 'name'::text, p_department_id uuid DEFAULT NULL::uuid)
 RETURNS TABLE(day integer, shift_id uuid, cnt bigint)
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  with picked as (
    select d.member_id
    from public.member_directory d
    where (p_branch_id is null or d.branch_id = p_branch_id)
      and (
        coalesce(p_search, '') = ''
        or (p_field = 'national_id' and d.national_id ilike '%' || p_search || '%')
        or (p_field = 'code' and d.member_code ilike '%' || p_search || '%')
        or (p_field not in ('national_id', 'code') and d.full_name ilike '%' || p_search || '%')
      )
      and (
        p_department_id is null
        or exists (
          select 1
          from public.member_departments md
          where md.member_id = d.member_id
            and md.year = p_year
            and md.month = p_month
            and md.department_id = p_department_id
        )
      )
  )
  select
    extract(day from rd.date)::integer as day,
    rd.shift_id,
    count(*)::bigint as cnt
  from public.roster_days rd
  join picked p on p.member_id = rd.member_id
  where rd.date >= make_date(p_year, p_month, 1)
    and rd.date < (make_date(p_year, p_month, 1) + interval '1 month')
  group by 1, 2;
$function$;
revoke all on function public.roster_day_totals(p_year integer, p_month integer, p_branch_id uuid, p_search text, p_field text, p_department_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.roster_day_totals(p_year integer, p_month integer, p_branch_id uuid, p_search text, p_field text, p_department_id uuid) to authenticated;

CREATE OR REPLACE FUNCTION public.roster_maker_data(p_year integer, p_month integer)
 RETURNS json
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_branch uuid;
  v_can    boolean;
begin
  select branch_id, can_make_roster into v_branch, v_can
  from public.members where profile_id = auth.uid();
  if not coalesce(v_can, false) then
    return json_build_object('members', '[]'::json, 'shifts', '[]'::json, 'roster', '[]'::json);
  end if;
  return json_build_object(
    'members', coalesce((
      select json_agg(json_build_object('member_id', md.member_id, 'code', md.member_code, 'full_name', md.full_name)
             order by md.full_name)
      from public.member_directory md where md.branch_id = v_branch), '[]'::json),
    'shifts', coalesce((
      select json_agg(json_build_object('id', s.id, 'key', s.key, 'name', s.name) order by s.name)
      from public.shifts s where s.key is not null), '[]'::json),
    'roster', coalesce((
      select json_agg(json_build_object('member_id', rd.member_id, 'day', extract(day from rd.date)::int, 'key', sh.key))
      from public.roster_days rd
      join public.shifts sh on sh.id = rd.shift_id
      join public.members m on m.id = rd.member_id
      where m.branch_id = v_branch
        and rd.date >= make_date(p_year, p_month, 1)
        and rd.date < (make_date(p_year, p_month, 1) + interval '1 month')), '[]'::json)
  );
end $function$;
revoke all on function public.roster_maker_data(p_year integer, p_month integer) from public, anon, authenticated, service_role;
grant execute on function public.roster_maker_data(p_year integer, p_month integer) to authenticated;

CREATE OR REPLACE FUNCTION public.server_now()
 RETURNS json
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  fz   timestamptz;
  eff  timestamptz;
  rnow timestamptz := now();
begin
  select i.frozen_at into fz from public.members i where i.profile_id = auth.uid() limit 1;
  eff := coalesce(fz, rnow);
  return json_build_object(
    'date', to_char((eff at time zone 'Africa/Cairo'), 'YYYY-MM-DD'),
    'time', to_char((eff at time zone 'Africa/Cairo'), 'HH24:MI:SS'),
    'frozen', fz is not null,
    'real_date', to_char((rnow at time zone 'Africa/Cairo'), 'YYYY-MM-DD'),
    'real_time', to_char((rnow at time zone 'Africa/Cairo'), 'HH24:MI:SS')
  );
end;
$function$;
revoke all on function public.server_now() from public, anon, authenticated, service_role;
grant execute on function public.server_now() to anon;
grant execute on function public.server_now() to authenticated;

CREATE OR REPLACE FUNCTION public.sync_attendance_with_roster()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if (tg_op = 'DELETE') then
    delete from public.attendance
     where member_id = old.member_id and date = old.date and shift_id = old.shift_id;
    return old;
  elsif (tg_op = 'UPDATE') then
    if new.shift_id is distinct from old.shift_id then
      delete from public.attendance
       where member_id = old.member_id and date = old.date and shift_id = old.shift_id;
    end if;
    return new;
  end if;
  return null;
end;
$function$;

