-- GENERATED by scripts/extract-programmables.mjs from a reference database.
-- RLS policies — the authorization model. See the note above.
-- Re-applied after every migration; every statement is idempotent.

alter table public.admin_assignments enable row level security;
alter table public.app_settings enable row level security;
alter table public.attachments enable row level security;
alter table public.attendance enable row level security;
alter table public.audit_log enable row level security;
alter table public.branches enable row level security;
alter table public.departments enable row level security;
alter table public.face_templates enable row level security;
alter table public.groups enable row level security;
alter table public.institutions enable row level security;
alter table public.member_departments enable row level security;
alter table public.members enable row level security;
alter table public.presence_checks enable row level security;
alter table public.presence_confirmations enable row level security;
alter table public.profiles enable row level security;
alter table public.qr_tokens enable row level security;
alter table public.roster_days enable row level security;
alter table public.shifts enable row level security;

drop policy if exists "assignments_select" on public.admin_assignments;
create policy "assignments_select" on public.admin_assignments
  as permissive for select to authenticated
  using (((admin_id = auth.uid()) OR is_superadmin()));

drop policy if exists "assignments_write_superadmin" on public.admin_assignments;
create policy "assignments_write_superadmin" on public.admin_assignments
  as permissive for all to authenticated
  using (is_superadmin())
  with check (is_superadmin());

drop policy if exists "settings_select" on public.app_settings;
create policy "settings_select" on public.app_settings
  as permissive for select to authenticated
  using (true);

drop policy if exists "settings_write_superadmin" on public.app_settings;
create policy "settings_write_superadmin" on public.app_settings
  as permissive for all to authenticated
  using (is_superadmin())
  with check (is_superadmin());

drop policy if exists "attendance_delete_superadmin" on public.attendance;
create policy "attendance_delete_superadmin" on public.attendance
  as permissive for delete to authenticated
  using (is_superadmin());

drop policy if exists "attendance_select" on public.attendance;
create policy "attendance_select" on public.attendance
  as permissive for select to authenticated
  using (((member_id = my_member_id()) OR (EXISTS ( SELECT 1
   FROM members i
  WHERE ((i.id = attendance.member_id) AND admin_can_access(i.group_id, attendance.branch_id))))));

drop policy if exists "attendance_update_superadmin" on public.attendance;
create policy "attendance_update_superadmin" on public.attendance
  as permissive for update to authenticated
  using (is_superadmin())
  with check (is_superadmin());

drop policy if exists "audit_insert_self" on public.audit_log;
create policy "audit_insert_self" on public.audit_log
  as permissive for insert to authenticated
  with check (((actor_id = auth.uid()) OR (actor_id IS NULL)));

drop policy if exists "audit_select_admin" on public.audit_log;
create policy "audit_select_admin" on public.audit_log
  as permissive for select to authenticated
  using (is_admin());

drop policy if exists "branches_select" on public.branches;
create policy "branches_select" on public.branches
  as permissive for select to authenticated
  using ((is_admin() OR (id IN ( SELECT members.branch_id AS hospital_id
   FROM members
  WHERE (members.profile_id = auth.uid())))));

drop policy if exists "branches_write_superadmin" on public.branches;
create policy "branches_write_superadmin" on public.branches
  as permissive for all to authenticated
  using (is_superadmin())
  with check (is_superadmin());

drop policy if exists "departments_select" on public.departments;
create policy "departments_select" on public.departments
  as permissive for select to authenticated
  using (true);

drop policy if exists "departments_write_admin" on public.departments;
create policy "departments_write_admin" on public.departments
  as permissive for all to authenticated
  using (is_admin())
  with check (is_admin());

drop policy if exists "face_delete_superadmin" on public.face_templates;
create policy "face_delete_superadmin" on public.face_templates
  as permissive for delete to authenticated
  using (is_superadmin());

drop policy if exists "face_insert_self" on public.face_templates;
create policy "face_insert_self" on public.face_templates
  as permissive for insert to authenticated
  with check ((member_id = my_member_id()));

drop policy if exists "face_select_self_or_admin" on public.face_templates;
create policy "face_select_self_or_admin" on public.face_templates
  as permissive for select to authenticated
  using (((member_id = my_member_id()) OR is_admin()));

drop policy if exists "face_update_self" on public.face_templates;
create policy "face_update_self" on public.face_templates
  as permissive for update to authenticated
  using ((member_id = my_member_id()))
  with check ((member_id = my_member_id()));

drop policy if exists "groups_select" on public.groups;
create policy "groups_select" on public.groups
  as permissive for select to authenticated
  using ((is_admin() OR (id IN ( SELECT members.group_id AS batch_id
   FROM members
  WHERE (members.profile_id = auth.uid())))));

drop policy if exists "groups_write_superadmin" on public.groups;
create policy "groups_write_superadmin" on public.groups
  as permissive for all to authenticated
  using (is_superadmin())
  with check (is_superadmin());

drop policy if exists "institutions_select" on public.institutions;
create policy "institutions_select" on public.institutions
  as permissive for select to authenticated
  using (true);

drop policy if exists "institutions_write_superadmin" on public.institutions;
create policy "institutions_write_superadmin" on public.institutions
  as permissive for all to authenticated
  using (is_superadmin())
  with check (is_superadmin());

drop policy if exists "member_departments_select" on public.member_departments;
create policy "member_departments_select" on public.member_departments
  as permissive for select to authenticated
  using (((member_id = my_member_id()) OR is_admin()));

drop policy if exists "member_departments_write_admin" on public.member_departments;
create policy "member_departments_write_admin" on public.member_departments
  as permissive for all to authenticated
  using (is_admin())
  with check (is_admin());

drop policy if exists "members_delete_superadmin" on public.members;
create policy "members_delete_superadmin" on public.members
  as permissive for delete to authenticated
  using (is_superadmin());

drop policy if exists "members_select" on public.members;
create policy "members_select" on public.members
  as permissive for select to authenticated
  using (((profile_id = auth.uid()) OR admin_can_access(group_id, branch_id)));

drop policy if exists "members_update_admin" on public.members;
create policy "members_update_admin" on public.members
  as permissive for update to authenticated
  using (admin_can_access(group_id, branch_id))
  with check (admin_can_access(group_id, branch_id));

drop policy if exists "profiles_delete_member_by_admin" on public.profiles;
create policy "profiles_delete_member_by_admin" on public.profiles
  as permissive for delete to authenticated
  using (((role = 'member'::role) AND is_admin()));

drop policy if exists "profiles_delete_superadmin" on public.profiles;
create policy "profiles_delete_superadmin" on public.profiles
  as permissive for delete to authenticated
  using (is_superadmin());

drop policy if exists "profiles_select_self_or_admin" on public.profiles;
create policy "profiles_select_self_or_admin" on public.profiles
  as permissive for select to authenticated
  using (((id = auth.uid()) OR is_admin()));

drop policy if exists "profiles_update_member_by_admin" on public.profiles;
create policy "profiles_update_member_by_admin" on public.profiles
  as permissive for update to authenticated
  using (((role = 'member'::role) AND is_admin()))
  with check (((role = 'member'::role) AND is_admin()));

drop policy if exists "profiles_update_superadmin" on public.profiles;
create policy "profiles_update_superadmin" on public.profiles
  as permissive for update to authenticated
  using (is_superadmin())
  with check (is_superadmin());

drop policy if exists "roster_days_select" on public.roster_days;
create policy "roster_days_select" on public.roster_days
  as permissive for select to authenticated
  using (((member_id = my_member_id()) OR is_admin()));

drop policy if exists "roster_days_write_admin" on public.roster_days;
create policy "roster_days_write_admin" on public.roster_days
  as permissive for all to authenticated
  using (is_admin())
  with check (is_admin());

drop policy if exists "shifts_select" on public.shifts;
create policy "shifts_select" on public.shifts
  as permissive for select to authenticated
  using (true);

drop policy if exists "shifts_write_superadmin" on public.shifts;
create policy "shifts_write_superadmin" on public.shifts
  as permissive for all to authenticated
  using (is_superadmin())
  with check (is_superadmin());

