-- GENERATED by scripts/extract-programmables.mjs from a reference database.
-- Scheduled jobs (pg_cron).
-- Re-applied after every migration; every statement is idempotent.

do $cron$
begin
  if exists (select 1 from cron.job where jobname = 'cleanup-expired-qr') then
    perform cron.unschedule('cleanup-expired-qr');
  end if;
end
$cron$;
select cron.schedule('cleanup-expired-qr', '* * * * *', 'delete from public.qr_tokens where expires_at < now() - interval ''1 minute''');

do $cron$
begin
  if exists (select 1 from cron.job where jobname = 'mark-left-work') then
    perform cron.unschedule('mark-left-work');
  end if;
end
$cron$;
select cron.schedule('mark-left-work', '*/15 * * * *', 'select public.mark_left_work();');

