-- GENERATED by scripts/extract-programmables.mjs from a reference database.
-- Rows the schema cannot work without.
-- Re-applied after every migration; every statement is idempotent.

insert into public.app_settings (id) values (1) on conflict (id) do nothing;
