-- GENERATED by scripts/extract-programmables.mjs from a reference database.
-- Triggers. Dropped and recreated so the definition is exact.
-- Re-applied after every migration; every statement is idempotent.

drop trigger if exists trg_branches_set_geom on public.branches;
CREATE TRIGGER trg_branches_set_geom BEFORE INSERT OR UPDATE OF latitude, longitude, area_coords ON public.branches FOR EACH ROW EXECUTE FUNCTION branches_set_geom();

drop trigger if exists members_assign_code on public.members;
CREATE TRIGGER members_assign_code BEFORE INSERT OR UPDATE OF group_id, member_code ON public.members FOR EACH ROW EXECUTE FUNCTION assign_member_code();

drop trigger if exists trg_sync_attendance_roster on public.roster_days;
CREATE TRIGGER trg_sync_attendance_roster AFTER DELETE OR UPDATE ON public.roster_days FOR EACH ROW EXECUTE FUNCTION sync_attendance_with_roster();

