// Migration runner — model-first, in three phases.
//
//   1. db/prelude.sql       extensions, roles and the auth/storage schemas.
//                           Idempotent: the first CREATE TABLE needs `vector`
//                           and the first CREATE POLICY needs `authenticated`.
//   2. db/functions/010      the functions ALONE, with check_function_bodies
//                           off. The policies in phase 3 call auth.uid() and
//                           current_app_role(), while those functions read
//                           tables phase 3 has not created yet — a genuine
//                           cycle. Postgres solves it the same way pg_dump
//                           does: create the bodies unvalidated now, and let
//                           phase 4 re-create them for real.
//   3. db/migrations/*.sql  generated by `npm run db:generate` from the models
//                           in src/db/schema. Applied ONCE each, in order.
//   4. db/functions/*.sql   functions, triggers, scheduled jobs, grants and the
//                           seed rows — everything drizzle-kit has no concept
//                           of. Every statement is CREATE OR REPLACE or an
//                           idempotent upsert, so the whole directory is
//                           RE-APPLIED after every run, validated this time.
//
// Phase 3 running every time is the point. A migration that renames a column
// leaves the function that reads it stale; re-applying the functions repairs
// them in the same run rather than at the next incident.
//
// Phase 2 is tracked in public._migrations with a checksum, so an applied file
// cannot be edited underneath a deployed environment.
//
//   node scripts/migrate.mjs [--status] [--dry-run]
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Umzug } from 'umzug';
import pg from 'pg';
import 'dotenv/config';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DB_DIR = join(ROOT, 'db');

const argv = process.argv.slice(2);
const flag = (name) => argv.includes(`--${name}`);

const sqlFiles = (dir) =>
  existsSync(dir) ? readdirSync(dir).filter((f) => f.endsWith('.sql')).sort() : [];

const sha = (text) => createHash('sha256').update(text).digest('hex').slice(0, 16);

/** Umzug storage backed by public._migrations. */
function pgStorage(client, pathOf) {
  return {
    async logMigration({ name }) {
      await client.query(
        `insert into public._migrations (id, lineage, checksum) values ($1, 'model', $2)
         on conflict (id) do update set checksum = excluded.checksum, applied_at = now()`,
        [name, sha(readFileSync(pathOf(name), 'utf8'))],
      );
    },
    async unlogMigration({ name }) {
      await client.query('delete from public._migrations where id = $1', [name]);
    },
    async executed() {
      const { rows } = await client.query(
        `select id from public._migrations where lineage = 'model' order by applied_at`,
      );
      return rows.map((r) => r.id);
    },
  };
}

/**
 * Apply one .sql file. Drizzle separates statements with `--> statement-breakpoint`
 * because some of them (CREATE INDEX CONCURRENTLY, ALTER TYPE ... ADD VALUE)
 * cannot share a transaction; honour that rather than sending the file whole.
 */
async function applyFile(client, body, { transactional = true } = {}) {
  const statements = body.includes('--> statement-breakpoint')
    ? body.split('--> statement-breakpoint').map((s) => s.trim()).filter(Boolean)
    : [body];
  const noTx = !transactional || /^\s*--\s*migrate:no-transaction\s*$/im.test(body);

  if (!noTx) await client.query('begin');
  try {
    for (const s of statements) await client.query(s);
    if (!noTx) await client.query('commit');
  } catch (err) {
    if (!noTx) await client.query('rollback').catch(() => {});
    throw err;
  }
}

function hint(message) {
  if (/password authentication failed/i.test(message)) {
    return [
      "",
      "Hint: Postgres applies POSTGRES_PASSWORD only when it FIRST initialises",
      "      its data directory. An existing volume keeps the password it was",
      "      created with, so changing POSTGRES_PASSWORD in .env afterwards",
      "      locks you out of your own database: the value in .env and the one",
      "      in the volume have simply diverged.",
      "",
      "      If the database is still empty, start it over:",
      "        docker compose down",
      "        docker volume rm intern-attendance_db-data",
      "",
      "      If it holds real data, change the password IN the database:",
      "        docker compose exec db psql -U attendance -d attendance \\",
      "          -c \"alter role attendance with password 'the-new-one'\"",
    ].join('\n');
  }

  if (/pg_cron|shared_preload_libraries/i.test(message)) {
    return (
      "\nHint: pg_cron needs shared_preload_libraries = 'pg_cron' in postgresql.conf\n" +
      '      and cron.database_name set to this database, then a restart.'
    );
  }
  if (/postgis|geography|vector/i.test(message)) {
    return (
      '\nHint: this schema needs postgis and pgvector available in the Postgres\n' +
      '      image (see server/docker/Dockerfile.postgres).'
    );
  }
  return '';
}

async function main() {
  if (!process.env.DATABASE_URL) {
    console.error('[migrate] DATABASE_URL is not set (copy .env.example to .env)');
    process.exit(1);
  }

  // Bounded retry. This runs as a container that starts the moment the database
  // reports healthy, and "healthy" and "accepting TCP connections" are not quite
  // the same instant — the entry point's initialisation server listens on the
  // unix socket only. Waiting a few seconds here is better than a failed deploy.
  //
  // A FRESH CLIENT PER ATTEMPT. node-postgres clients are single-use: once a
  // connect() has failed, the same object refuses every later attempt with
  // "Client has already been connected. You cannot reuse a client." Retrying on
  // one client meant the loop never retried anything — it spun for the full
  // sixty seconds and then reported that message as if it were the reason the
  // database was unreachable. Which is how a first deploy on a fresh server
  // failed with an error naming the wrong problem.
  const connect = async () => {
    const client = new pg.Client({
      connectionString: process.env.DATABASE_URL,
      ssl: process.env.DATABASE_SSL === '1' ? { rejectUnauthorized: false } : undefined,
    });
    await client.connect();
    return client;
  };

  const deadline = Date.now() + 60_000;
  let client;
  let lastError;
  for (;;) {
    try {
      client = await connect();
      break;
    } catch (err) {
      lastError = err;
      if (Date.now() > deadline) {
        console.error(`[migrate] could not connect within 60s: ${lastError.message}`);
        process.exit(1);
      }
      await new Promise((r) => setTimeout(r, 1000));
    }
  }

  const migrationsDir = join(DB_DIR, 'migrations');
  const names = sqlFiles(migrationsDir);
  const pathOf = (name) => join(migrationsDir, name);

  await client.query(`
    create table if not exists public._migrations (
      id         text primary key,
      lineage    text not null,
      checksum   text not null,
      applied_at timestamptz not null default now()
    )
  `);

  if (flag('status')) {
    const { rows } = await client.query(
      `select id from public._migrations where lineage = 'model'`,
    );
    const done = new Set(rows.map((r) => r.id));
    for (const n of names) console.log(`  ${done.has(n) ? 'applied' : 'pending'}  ${n}`);
    console.log(`\n${done.size}/${names.length} applied`);
    await client.end();
    return;
  }

  /* ------------------------------------------- 0. is this schema already here? */
  //
  // A database restored from the old Supabase project already HAS the schema —
  // it just has none of this runner's bookkeeping. Applying the generated
  // migration to it fails on the first line with `type "attendance_status"
  // already exists`, which says nothing about what to do.
  //
  // The fix is to record the migrations as applied without running them, so the
  // repeatable phase (policies, functions, grants) still runs. That is a
  // deliberate act, so it is a flag rather than something guessed.
  const { rows: modelApplied } = await client.query(
    `select count(*)::int as n from public._migrations where lineage = 'model'`,
  );
  const { rows: schemaPresent } = await client.query(
    `select to_regclass('public.profiles') is not null as present`,
  );
  const preexisting = modelApplied[0].n === 0 && schemaPresent[0].present;

  if (preexisting && !flag('adopt-baseline')) {
    console.error(
      '\n[migrate] this database already has the schema, but none of these\n' +
        '          migrations are recorded as applied. That is what a database\n' +
        '          restored from the old Supabase project looks like.\n\n' +
        '          Applying them would try to create everything a second time.\n' +
        '          To record them as applied and run only the repeatable files:\n\n' +
        '            npm run migrate -- --adopt-baseline\n\n' +
        '          Verify first that the schema really does match the models:\n' +
        '            npm run verify:schema\n',
    );
    process.exit(1);
  }

  try {
    /* ------------------------------------------------------------- 1. prelude */
    process.stdout.write('  prelude ... ');
    await applyFile(client, readFileSync(join(DB_DIR, 'prelude.sql'), 'utf8'));
    console.log('ok');

    /* --------------------------------------------- 2. functions, unvalidated */
    const fnFile = join(DB_DIR, 'functions', '010_functions.sql');
    if (existsSync(fnFile)) {
      process.stdout.write('  functions (unvalidated, for the policies) ... ');
      // Scoped to this transaction, so nothing later escapes validation.
      await client.query('begin');
      try {
        await client.query('set local check_function_bodies = off');
        await client.query(readFileSync(fnFile, 'utf8'));
        await client.query('commit');
      } catch (err) {
        await client.query('rollback').catch(() => {});
        throw err;
      }
      console.log('ok');
    }

    /* ---------------------------------------------------------- 3. migrations */
    // Editing an applied migration silently desynchronises environments.
    const { rows: applied } = await client.query(
      `select id, checksum from public._migrations where lineage = 'model'`,
    );
    for (const rec of applied) {
      if (!names.includes(rec.id)) continue;
      if (sha(readFileSync(pathOf(rec.id), 'utf8')) !== rec.checksum) {
        console.error(
          `\n[migrate] ${rec.id} changed after it was applied.\n` +
            `          Change the models and generate a NEW migration instead.`,
        );
        process.exit(1);
      }
    }

    const umzug = new Umzug({
      migrations: names.map((name) => ({
        name,
        up: () => applyFile(client, readFileSync(pathOf(name), 'utf8')),
        down: async () => {
          throw new Error(`${name} has no down migration — restore from a backup`);
        },
      })),
      context: {},
      storage: pgStorage(client, pathOf),
      logger: undefined,
    });

    if (flag('dry-run')) {
      const pending = await umzug.pending();
      for (const m of pending) console.log(`  would apply  ${m.name}`);
      console.log(`\n[migrate] ${pending.length} pending; db/functions would be re-applied.`);
      return;
    }

    let ran = [];
    if (preexisting) {
      // Adopting: the schema is already there, so record the migrations rather
      // than run them. The repeatable phase below still runs, which is what
      // brings the policies, functions and grants in line.
      const pending = await umzug.pending();
      for (const m of pending) {
        process.stdout.write(`  adopting  ${m.name} ... `);
        await umzug.options.storage.logMigration({ name: m.name, context: {} });
        console.log('ok');
      }
      ran = pending;
    } else {
      umzug.on('migrating', ({ name }) => process.stdout.write(`  applying  ${name} ... `));
      umzug.on('migrated', () => console.log('ok'));
      ran = await umzug.up();
    }

    /* ------------------------------------------------------------ 4. functions */
    // Always, not only when something changed: this is what repairs a function
    // whose table just moved underneath it.
    const repeatable = sqlFiles(join(DB_DIR, 'functions'));
    for (const name of repeatable) {
      process.stdout.write(`  re-applying  functions/${name} ... `);
      await applyFile(client, readFileSync(join(DB_DIR, 'functions', name), 'utf8'));
      console.log('ok');
    }

    console.log(
      `\n[migrate] ${ran.length} migration(s) applied, ` +
        `${repeatable.length} repeatable file(s) re-applied.`,
    );
  } catch (err) {
    console.log('FAILED');
    console.error(`\n${err.message}${hint(err.message)}\n`);
    process.exit(1);
  } finally {
    await client.end();
  }
}

main().catch((err) => {
  console.error(err.message ?? err);
  process.exit(1);
});
